### ISSUE TITLE
一直卡在同一节课

### ISSUE THREAD

**Issue by a77uu** [sheng33/selenium-001#2]
重新登录后一直在1-1的第一节课 完成度100后 也无法跳到下一节

**Comment by sheng33** [comment]
> 重新登录后一直在1-1的第一节课完成度100后也无法跳到下一段
请问你下一节课是什么？ppt还是视频或者其他的？

**Comment by sheng33** [comment]
> 重新登录后一直在1-1的第一节课完成度100后也无法跳到下一段

如果下面也还是ppt或者视频话。重复完成度100三次左右应该就会进行下一个

**Comment by a77uu** [comment]
![MGAqwF.png](https://s2.ax1x.com/2019/11/13/MGAqwF.png)
就差不多是这种状态~
